io:
  muenchendigital:
    digiwf:
      okewo:
        password: ''
        url: ''
        username: ''
        benutzerId: ''
      streaming:
        typeMappings:
          getPerson: getPerson
          getPersonErweitert: getPersonErweitert
          searchPerson: searchPerson
          searchPersonErweitert: searchPersonErweitert
spring:
  cloud:
    function:
      definition: functionRouter;sendMessage;sendCorrelateMessage;
    stream:
      bindings:
        functionRouter-in-0:
          destination: <topic>
          group: <groupId>
        sendCorrelateMessage-out-0:
          destination: <topic>
        sendMessage-out-0:
          destination: <topic>
      kafka:
        binder:
          brokers: <brokerUrl>
          configuration:
            security:
              protocol: SSL
          consumerProperties:
            auto:
              offset:
                reset: latest
            key:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          producerProperties:
            key:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    ssl:
      key-password: ''
      key-store-location: ''
      key-store-password: ''
      trust-store-location: ''
      trust-store-password: ''
